// GetRegions

GET http://localhost:3000/oracle/GetRegions

###

// InsertRegions

POST http://localhost:3000/oracle/InsertRegions
Content-Type: application/json

{
    "p_region":"p_region",
    "p_name":"p_name"
}

###

//UpdateRegion

PATCH http://localhost:3000/oracle/UpdateRegion
Content-Type: application/json

{
    "p_regionID": ,
    "p_name":"p_name"
}

###

// GetAllServiceproviders

GET http://localhost:3000/oracle/GetAllServiceproviders

###

//GetSelectedServiceprovider

GET http://localhost:3000/oracle/GetSelectedServiceprovider
Content-Type: application/json

{
    "p_spid":12
}

###

//InsertNewServiceProvider

POST http://localhost:3000/oracle/InsertNewServiceProvider
Content-Type: application/json

{
    "p_name": "Service Provider Name",
    "p_lookupcode": "SP001",
    "p_address1": "123 Main St",
    "p_address2": "Suite 100",
    "p_city": "Anytown",
    "p_state": "CA",
    "p_zip": "90210",
    "p_country": "USA",
    "p_issuingregion": "Region A",
    "p_replacementregion": "Region B",
    "p_bondsurety": "Surety Co.",
    "p_cargopolicyno": "CP123456",
    "p_cargosurety": "Cargo Surety Co.",
    "p_user_id": "user123"
}

###

//UpdateServiceProvider

PUT http://localhost:3000/oracle/UpdateServiceProvider
Content-Type: application/json

{
    "p_spid": 1,
    "p_name": "Service Provider Name",
    "p_lookupcode": "SP001",
    "p_address1": "123 Main St",
    "p_address2": "Suite 100",
    "p_city": "Anytown",
    "p_state": "CA",
    "p_zip": "90210",
    "p_country": "USA",
    "p_issuingregion": "Region A",
    "p_replacementregion": "Region B",
    "p_bondsurety": "Surety Co.",
    "p_cargopolicyno": "CP123456",
    "p_cargosurety": "Cargo Surety Co.",
    "p_user_id": "user123"
}

###

//GetSPcontacts

GET http://localhost:3000/oracle/GetSPcontacts
Content-Type: application/json

{
    "p_SPid":12
}

###

//GetSPDefaultcontact

###

//InsertSPContacts

POST http://localhost:3000/oracle/InsertSPContacts
Content-Type: application/json

{
    "p_spid": 12345,
    "p_firstname": "John",
    "p_lastname": "Doe",
    "p_title": "Mr.",
    "p_phoneno": "123-456-7890",
    "p_mobileno": "098-765-4321",
    "p_faxno": "123-456-7891",
    "p_emailaddress": "john.doe@example.com",
    "p_user_id": "jdoe"
}

###

//UpdateSPContacts

PUT http://localhost:3000/oracle/UpdateSPContacts
Content-Type: application/json

{
    "p_spcontactid": 12345,
    "p_firstname": "Jane",
    "p_lastname": "Doe",
    "p_title": "Ms.",
    "p_phoneno": "123-456-7890",
    "p_mobileno": "098-765-4321",
    "p_faxno": "123-456-7891",
    "p_emailaddress": "jane.doe@example.com",
    "p_user_id": "jdoe"
}

###

//SetSPDefaultcontact


###

//InactivateSPContact



###


